- name: test 2 lists
  hosts: localhost
  gather_facts: false
  vars:
    list1: [foo2]
    list2: [foo2]
  
  tasks: 
  - name: test
    debug:
      msg: "true"
    when: (list1 | intersect(list2) | length) > 0

    