---

- name: Cisco IOS
  hosts: iosvl2-1  
  gather_facts: false
  connection: network_cli
  vars:
    - ansible_playbook_python: "{{ ansible_python_interpreter }}"

  tasks: 
  - name: gather fact ios
    cisco.ios.ios_facts: 
      gather_network_resources: 
        - "l2_interfaces"
        - "vlans"
      gather_subset:
        - '!all'
        - 'min'
    register: ios_fact
    become: true
  
  - name: print IOS facts
    debug:
      var: ios_fact

- name: Juniper JunOS
  hosts: vqfx1 
  gather_facts: false
  connection: network_cli

  tasks: 
  - name: gather fact junos
    junipernetworks.junos.junos_facts:
      gather_subset:
        - '!all'
        - 'min'
      gather_network_resources: 
        - vlans
        - l2_interfaces
    register: junos_fact
  
  - name: print junos facts
    debug:
      var: junos_fact